from pathlib import Path
from typing import Any, Dict, List, Union

def parse_openair_file(filepath: str) -> str: ...
def parse_openair_string(data: str) -> str: ...
def parse_file(filepath: Union[str, Path]) -> List[Dict[str, Any]]: ...
def parse_string(data: str) -> List[Dict[str, Any]]: ...
